codecov:
  token: ba4d1ad0-2aaf-4569-983c-4013b607927e

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: "new"
  require_changes: false
  after_n_builds: 3

coverage:
  status:
    project:
      default:
        target: 85%  # Set your overall project coverage target
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%  # Coverage target for patches
        threshold: 0.5%

flags:
  api-gateway:
    paths:
      - "api-gateway/src/**"
  discovery-server:
    paths:
      - "discovery-server/src/**"
  inventory-service:
    paths:
      - "inventory-service/src/**"
  notification-service:
    paths:
      - "notification-service/src/**"
  order-service:
    paths:
      - "order-service/src/**"
  product-service:
    paths:
      - "product-service/src/**"

ignore:
  - "**/test/**"  # Ignore test files
  - "**/docs/**"
  - "**/generated/**"  # Ignore generated files (e.g., from OpenAPI)

fixes:
  - "**/generated/**"  # Skip generated files from coverage

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

exclude_lines:
  - "assert\(.*\);"
  - "if \(false\) \{.*\}"  # Exclude unreachable code
  - "LOG\.(info|debug|warn|error)\("

