# .github/workflows/java-ci.yml
name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean Maven project
        run: mvn clean

  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4.2
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Docker container
        run: docker run --name mongo -p 27017:27017 -d mongo:4.4.2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker
          docker --version

      - name: Build and test Maven project
        run: mvn test
